name: Python package

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # or whichever version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install numpy
        pip install scipy
        pip install pybind11
        pip install sklearn
        pip install rdata
        wget https://gitlab.com/libeigen/eigen/-/archive/3.4.0/eigen-3.4.0.tar.gz
        tar -xzf eigen-3.4.0.tar.gz

    - name: Install build tools
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake

    - name: Build the C++ extension
      run: |
        cd src
        python setup.py build_ext --inplace

    - name: Run tests
      run: |
        pytest test_check_data.py
        pytest test_HandleNumericAndNan.py     
        pytest test_GetBinnedCurve.py
        pytest test_GetBinnedDataset.py
        pytest test_Minb.py
        pytest test_ConvertSupport.py
        pytest test_MapX1D.py
        pytest test_gcvlwls1d1.py
        pytest test_CVLwls1D.py
